---
version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/New_York
      - SUBDOMAINS=addsubdomains,seperatedbycommas
      - TOKEN=add-duckdns-token
      - LOG_FILE=false #optional
    volumes:
      - /absolute-path-to-config-file:/config #optional
    restart: unless-stopped 